### ISSUE TITLE
1.19.2+ Compatibility

### ISSUE THREAD

**Issue by GlimmerDev** [connor135246/Simply-Hot-Springs#10]
The mod is not currently compatible with version 1.19. Ideally, a version for 1.19.2-1.19.4 would be appreciated.

**Comment by connor135246** [comment]
Working on a 1.19.2 version. It'll be out soon.

I actually already did most of the work back when 1.19.2 came out, but Forge's fluid changes in 1.19 left a lot to be desired... I hoped that if I waited they would fix things, but it seems that didn't happen.

**Comment by connor135246** [comment]
It's out. Sorry for the wait!
