### ISSUE TITLE
[1.18.2]  Crash on Worldgen

### ISSUE THREAD

**Issue by Reshy** [connor135246/Simply-Hot-Springs#11]
![image](https://github.com/connor135246/Simply-Hot-Springs/assets/2096384/a2432ed5-44b4-4194-b485-5c35cdcb735f)

https://pastebin.com/RBFAw4Qp

**Comment by connor135246** [comment]
Thanks for the report. I believe this is an easy fix.

**Comment by connor135246** [comment]
The fix is released as v1.18.2-0.2.6.
