### ISSUE TITLE
[Question] use ceiling aware heightmap for non-hotspring?

### ISSUE THREAD

**Issue by KazuMurako** [connor135246/Simply-Hot-Springs#12]
In 1.19.2 can the ceiling aware heightmap be used to generate custom structures other than hot springs using datapacks?

**Comment by connor135246** [comment]
Yes. It works just like any other placement modifier.

**Comment by KazuMurako** [comment]
So if I was making a dungeon that I wanted to spawn in the nether, I would put the line "project_start_to_heightmap": "simplyhotsprings:ceiling_aware_heightmap" in my [namespace]/worldgen/structure/nether_dungeon.json?

**Comment by connor135246** [comment]
Sorry, my mistake - it can't be used in custom _structures_, only custom _features_. 
It can't be used with "project_start_to_heightmap" because that option only accepts a heightmap. "simplyhotsprings:ceiling_aware_heightmap" is a feature placement modifier, not a heightmap.

**Comment by KazuMurako** [comment]
Understood, thank you.
