### ISSUE TITLE
Render Conflict with Recurrent Complex

### ISSUE THREAD

**Issue by mallrat208** [connor135246/Simply-Hot-Springs#3]
This was tested using the following mods:
Forge 14.23.5.2854
Simply Hot Springs 0.1.1
Recurrent Complex 1.4.8.2
IvToolkit 1.3.3-1.12

With Simply Hot Springs loaded, the selection box used to define selections with Recurrent Complex either doesn't (seem to) render. Removing Simply Hot Springs from the instance causes them to render again.

I *think* it might be an issue of the GlStateManager not being reset after you're done handling your particle stuff. I'm however not that well read when it comes to that side of rendering.

**Comment by connor135246** [comment]
Fixed in v0.1.2
