### ISSUE TITLE
[BUG] Server Crash + Repo License 

### ISSUE THREAD

**Issue by yeelp** [connor135246/Simply-Hot-Springs#4]
Any dedicated server running SimplyHotSprings crashes.

The problem stems from ClientProxy, specifically https://github.com/connor135246/Simply-Hot-Springs/blob/a7fe08f9ad65f02fdd374b93f9035b3f58b52644/src/main/java/connor135246/simplyhotsprings/client/ClientProxy.java#L25

The `@EventBusSubscriber`  registers the ClientProxy when the `@Mod` class is constructed, which obviously happens on both the client and server sides, but of course, the ClientProxy is supposed to only be registered client side. As a result, somewhere down the line, you run into [this crash](https://pastebin.com/8G6R4pgq).

The fix *should* be really simple, assuming there aren't other issues present. All you have to do is indicate that the ClientProxy is supposed to be registered on the client side only. You can do this by adding an optional argument to the `@EventBusSubscriber`:

```@EventBusSubscriber(value = Side.CLIENT)```

You can read more about how this works [here](https://mcforge.readthedocs.io/en/latest/events/intro/#automatically-registering-static-event-handlers) (this documentation uses 1.16's "architecture", so the only difference as far as I'm aware that's relevant is that in 1.16, `Side` was changed to `Dist` for the `@EventBusSubscriber`).

Lastly, you really should add a license to this repo. CurseForge indicates this mod has a GNU General Public License but GitHub lists none.

**Comment by connor135246** [comment]
Whoops, that's pretty embarrassing that I didn't try pressing runServer at least once in testing...

Fixed in v0.2.0.
