### ISSUE TITLE
IMPORTANT Question about Hot Spring Water!!

### ISSUE THREAD

**Issue by Revelins** [connor135246/Simply-Hot-Springs#5]
Hey, 

So I know this is a lot to ask, but I'm wondering if this mod would ever be updated to 1.16+? Me and my friend have LOVED this from Biomes O' Plenty and we had an on-going bit where we hunted for it. Since then, Biomes O' Plenty has removed this liquid entirely from their mod. I tried updating this mod manually with the source code but my coding program was left with hundreds of errors. Do you think you'd ever consider updating it? If not, I entirely understand, I know a random mod about hot springs is most likely not worth your time.

**Comment by connor135246** [comment]
I'm not guaranteeing anything at this point, but Forge or Fabric?

**Comment by Revelins** [comment]
Whichever you're more comfortable coding with! If it's too much trouble, then don't worry about it, though. Thanks for considering it regardless!

**Comment by connor135246** [comment]
Here it is!
https://www.curseforge.com/minecraft/mc-mods/simply-hot-springs/files/3587349
