### ISSUE TITLE
Config comments no longer generate

### ISSUE THREAD

**Issue by democat3457** [connor135246/Simply-Hot-Springs#6]
When I upgraded from 0.2.0 to 0.2.2, the config comments disappeared! (probably due to you switching the `@Comment` to `@LangKey`)
<img width="413" alt="Screen Shot 2022-01-01 at 3 21 41 AM" src="https://user-images.githubusercontent.com/32407067/147847701-7109ea7b-9322-48c1-83c3-ed8a8c684367.png">

Also, the `#How to fill Whitelists and Blacklists` is useless now that the comment is gone lol

**Comment by connor135246** [comment]
Oops. Well, for now you can still read the comments on the in-game config GUI screen.

**Comment by connor135246** [comment]
Fixed in v0.2.3
