### ISSUE TITLE
Incompatibility with REI

### ISSUE THREAD

**Issue by 07Ravioli** [connor135246/Simply-Hot-Springs#7]
I'm roughly new to anything involving mods but I used to use BOP in 1.12 and I updated to 1.16 and found this mod to heal my soul from missing the hot springs, but I tried placing the water down and nothing happened, I reinstalled all my mods one by one, and it seems that whenever I have roughly enough items in my mods folder it does not like to cooperate. if I made a dumb mistake, I'm sorry but please help me out, I adore this mod and would love to use it.

**Comment by connor135246** [comment]
Thanks for letting me know!
This appears to be an issue with REI, since it also seems to happen with other mods that add fluid buckets. 
[I've made a bug report on REI's github.](https://github.com/shedaniel/RoughlyEnoughItems/issues/847)

**Comment by 07Ravioli** [comment]
> Thanks for letting me know! This appears to be an issue with REI, since it also seems to happen with other mods that add fluid buckets. [I've made a bug report on REI's github.](https://github.com/shedaniel/RoughlyEnoughItems/issues/847)

Thank you very much, this may be a issue on my part but it also doesnt allow lilly pads from other mods such as terra incognita, no worries about it though.
